name: pfp-env
channels:
  - defaults
dependencies:
  - flake8==3.8.3=py_0
  - mypy
  - pytest==6.0.1=py38_0
  - scipy=1.5.0
  - click=7.1.2
  - more-itertools==8.4.0=py_0
  - pyparsing==2.4.7=py_0
  - mccabe==0.6.1=py38_1
  - certifi
  - packaging==20.4=py_0
  - pip==20.2.2=py38_0
  - wheel==0.34.2=py38_0
  - pycodestyle==2.6.0=py_0
  - iniconfig==1.0.1=py_0
  - pyflakes==2.2.0=py_0
  - mypy_extensions==0.4.3=py38_0
  - importlib-metadata==1.7.0=py38_0
  - py==1.9.0=py_0
  - zipp==3.1.0=py_0
  - ca-certificates
  - toml==0.10.1=py_0
  - attrs==19.3.0=py_0
  - six==1.15.0=py_0
  - typing_extensions==3.7.4.2=py_0
  - setuptools==49.6.0=py38_0
  - pluggy==0.13.1=py38_0
  - ipykernel
  - numpy
  - pandas
  - opendssdirect-py
